# Generated by Django 5.1.2 on 2024-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('year_of_graduation', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('current_job_title', models.CharField(max_length=100)),
                ('current_company', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('career_path', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('mentorship_expertise', models.TextField(blank=True)),
                ('preferred_interaction_mode', models.CharField(choices=[('email', 'Email'), ('video_call', 'Video Call'), ('in_person', 'In Person')], max_length=50)),
                ('time_commitment', models.IntegerField(blank=True, help_text='Available hours per month', null=True)),
                ('interested_in_career_talks', models.BooleanField(default=False)),
                ('access_to_opportunities', models.BooleanField(default=False)),
                ('willing_to_donate', models.BooleanField(default=False)),
                ('event_participation', models.BooleanField(default=False)),
                ('other_contributions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('current_year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('career_interests', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mentorship_goals', models.TextField(blank=True)),
                ('preferred_industry', models.CharField(blank=True, max_length=100)),
                ('preferred_company', models.CharField(blank=True, max_length=100)),
                ('time_availability', models.IntegerField(blank=True, help_text='Available hours for mentorship', null=True)),
                ('interested_in_internships', models.BooleanField(default=False)),
                ('willing_to_attend_events', models.BooleanField(default=False)),
                ('specific_alumni_to_connect', models.TextField(blank=True)),
                ('open_to_mentoring_juniors', models.BooleanField(default=False)),
                ('networking_groups', models.BooleanField(default=False)),
            ],
        ),
    ]
