# Generated by Django 5.1.2 on 2024-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumni_profile_picture_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(blank=True, default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='time_commitment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_availability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
