# Generated by Django 5.1.2 on 2024-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_alumni_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
